name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o ./published
    - name: Copy
      run: |
        Copy-Item ./published/* C:/WSDemo -Recurse -Force
    - name: Setup Service
      run: |
        sc stop WSDemo
				sc delete WSDemo
				sc create WSDemo binPath= C:\WSDemo\WorkerDemo.exe
				sc start WSDemo
