name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o ./published
    - name: Copy
      run: |
        Copy-Item ./published/* C:/WSDemo -Recurse -Force
    - name: Service Stop
      run: |
        If (Get-Service "WSDemo" -ErrorAction SilentlyContinue) {
                    If ((Get-Service "WSDemo").Status -eq 'Running') {
                         # service exists and is running, so stop it first
                        Write-Output "Stopping service: $serviceName"
                        Stop-Service "WSDemo"
                    }
        }
    - name: Service create
      run: |
        New-Service -Name "WSDemo" -BinaryPathName '"C:\WSDemo\WorkerDemo.exe"'
    - name: Service start
      run: |
        Start-Service -Name "WSDemo"
